# Generated by Django 5.2 on 2025-04-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jardins',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
