# Generated by Django 5.2 on 2025-04-30 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_jardins_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='jardins',
            name='data_jardins',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
